<?php

use Drupal\Core\Entity\EntityInterface;

function licenta_base_node_presave(EntityInterface $node) {
  if (empty($node->field_task_number->value)) {
    $nids = \Drupal::entityQuery('node')->condition('type', 'task')->execute();
    $nodes = \Drupal\node\Entity\Node::loadMultiple($nids);
    $max = 0;
    foreach ($nodes as $task) {
      if ($task->field_task_number->value > $max) {
        $max = $task->field_task_number->value;
      }
    }
    $node->field_task_number->value = $max + 1;
  }
}
